#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbAMS")]
	public partial class eHRISContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRole(Role instance);
    partial void UpdateRole(Role instance);
    partial void DeleteRole(Role instance);
    partial void InsertEvaluationLINQ(EvaluationLINQ instance);
    partial void UpdateEvaluationLINQ(EvaluationLINQ instance);
    partial void DeleteEvaluationLINQ(EvaluationLINQ instance);
    partial void InsertEvaluation_Score(Evaluation_Score instance);
    partial void UpdateEvaluation_Score(Evaluation_Score instance);
    partial void DeleteEvaluation_Score(Evaluation_Score instance);
    #endregion
		
		public eHRISContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbAMS"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public eHRISContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eHRISContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eHRISContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eHRISContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<EvaluationLINQ> EvaluationLINQs
		{
			get
			{
				return this.GetTable<EvaluationLINQ>();
			}
		}
		
		public System.Data.Linq.Table<Evaluation_Score> Evaluation_Scores
		{
			get
			{
				return this.GetTable<Evaluation_Score>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _RoleId;
		
		private System.Guid _ApplicationId;
		
		private string _RoleName;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Evaluation")]
	public partial class EvaluationLINQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _EvaluationType;
		
		private System.Nullable<System.Guid> _EvaluatedById;
		
		private string _DateEvaluated;
		
		private System.Nullable<decimal> _TotalScore;
		
		private string _RemarksName;
		
		private string _ImpUnacceptable;
		
		private string _ImpFallShort;
		
		private string _ImpEffective;
		
		private string _ImpHighlyEffective;
		
		private string _ImpExceptional;
		
		private string _Recommendation;
		
		private string _NeedImprovement;
		
		private System.Nullable<System.Guid> _ApprovedByManagerId;
		
		private System.Nullable<System.Guid> _ApprovedByHRId;
		
		private string _EmployeesCreativeContribution;
		
		private string _EmployeesNewSkills;
		
		private string _EmployeesStrength;
		
		private string _EmployeesImprovement;
		
		private string _EmployeesChanges;
		
		private string _EmployeesPersonalGoals;
		
		private string _EmployeesRecommendation;
		
		private string _Agency;
		
		private System.Nullable<decimal> _Section1A;
		
		private System.Nullable<decimal> _Section1B;
		
		private System.Nullable<decimal> _Section1C;
		
		private System.Nullable<decimal> _Section2A;
		
		private System.Nullable<decimal> _Section2B;
		
		private System.Nullable<decimal> _Section2C;
		
		private System.Nullable<decimal> _Section3A;
		
		private System.Nullable<decimal> _Section3B;
		
		private System.Nullable<decimal> _Section3C;
		
		private System.Nullable<decimal> _Section3D;
		
		private System.Nullable<decimal> _Section3E;
		
		private System.Nullable<decimal> _Section3F;
		
		private string _CommentSection1A;
		
		private string _CommentSection1B;
		
		private string _CommentSection1C;
		
		private string _CommentSection2A;
		
		private string _CommentSection2B;
		
		private string _CommentSection2C;
		
		private string _CommentSection3A;
		
		private string _CommentSection3B;
		
		private string _CommentSection3C;
		
		private string _CommentSection3D;
		
		private string _CommentSection3E;
		
		private string _CommentSection3F;
		
		private System.Nullable<int> _DaysSick;
		
		private System.Nullable<int> _DaysTardy;
		
		private string _primeComments;
		
		private string _NextEvaluationDate;
		
		private string _EnableManagerStrength;
		
		private string _EnableNeedImprovement;
		
		private string _EnableRemarks;
		
		private EntitySet<Evaluation_Score> _Evaluation_Scores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnEvaluationTypeChanging(string value);
    partial void OnEvaluationTypeChanged();
    partial void OnEvaluatedByIdChanging(System.Nullable<System.Guid> value);
    partial void OnEvaluatedByIdChanged();
    partial void OnDateEvaluatedChanging(string value);
    partial void OnDateEvaluatedChanged();
    partial void OnTotalScoreChanging(System.Nullable<decimal> value);
    partial void OnTotalScoreChanged();
    partial void OnRemarksNameChanging(string value);
    partial void OnRemarksNameChanged();
    partial void OnImpUnacceptableChanging(string value);
    partial void OnImpUnacceptableChanged();
    partial void OnImpFallShortChanging(string value);
    partial void OnImpFallShortChanged();
    partial void OnImpEffectiveChanging(string value);
    partial void OnImpEffectiveChanged();
    partial void OnImpHighlyEffectiveChanging(string value);
    partial void OnImpHighlyEffectiveChanged();
    partial void OnImpExceptionalChanging(string value);
    partial void OnImpExceptionalChanged();
    partial void OnRecommendationChanging(string value);
    partial void OnRecommendationChanged();
    partial void OnNeedImprovementChanging(string value);
    partial void OnNeedImprovementChanged();
    partial void OnApprovedByManagerIdChanging(System.Nullable<System.Guid> value);
    partial void OnApprovedByManagerIdChanged();
    partial void OnApprovedByHRIdChanging(System.Nullable<System.Guid> value);
    partial void OnApprovedByHRIdChanged();
    partial void OnEmployeesCreativeContributionChanging(string value);
    partial void OnEmployeesCreativeContributionChanged();
    partial void OnEmployeesNewSkillsChanging(string value);
    partial void OnEmployeesNewSkillsChanged();
    partial void OnEmployeesStrengthChanging(string value);
    partial void OnEmployeesStrengthChanged();
    partial void OnEmployeesImprovementChanging(string value);
    partial void OnEmployeesImprovementChanged();
    partial void OnEmployeesChangesChanging(string value);
    partial void OnEmployeesChangesChanged();
    partial void OnEmployeesPersonalGoalsChanging(string value);
    partial void OnEmployeesPersonalGoalsChanged();
    partial void OnEmployeesRecommendationChanging(string value);
    partial void OnEmployeesRecommendationChanged();
    partial void OnAgencyChanging(string value);
    partial void OnAgencyChanged();
    partial void OnSection1AChanging(System.Nullable<decimal> value);
    partial void OnSection1AChanged();
    partial void OnSection1BChanging(System.Nullable<decimal> value);
    partial void OnSection1BChanged();
    partial void OnSection1CChanging(System.Nullable<decimal> value);
    partial void OnSection1CChanged();
    partial void OnSection2AChanging(System.Nullable<decimal> value);
    partial void OnSection2AChanged();
    partial void OnSection2BChanging(System.Nullable<decimal> value);
    partial void OnSection2BChanged();
    partial void OnSection2CChanging(System.Nullable<decimal> value);
    partial void OnSection2CChanged();
    partial void OnSection3AChanging(System.Nullable<decimal> value);
    partial void OnSection3AChanged();
    partial void OnSection3BChanging(System.Nullable<decimal> value);
    partial void OnSection3BChanged();
    partial void OnSection3CChanging(System.Nullable<decimal> value);
    partial void OnSection3CChanged();
    partial void OnSection3DChanging(System.Nullable<decimal> value);
    partial void OnSection3DChanged();
    partial void OnSection3EChanging(System.Nullable<decimal> value);
    partial void OnSection3EChanged();
    partial void OnSection3FChanging(System.Nullable<decimal> value);
    partial void OnSection3FChanged();
    partial void OnCommentSection1AChanging(string value);
    partial void OnCommentSection1AChanged();
    partial void OnCommentSection1BChanging(string value);
    partial void OnCommentSection1BChanged();
    partial void OnCommentSection1CChanging(string value);
    partial void OnCommentSection1CChanged();
    partial void OnCommentSection2AChanging(string value);
    partial void OnCommentSection2AChanged();
    partial void OnCommentSection2BChanging(string value);
    partial void OnCommentSection2BChanged();
    partial void OnCommentSection2CChanging(string value);
    partial void OnCommentSection2CChanged();
    partial void OnCommentSection3AChanging(string value);
    partial void OnCommentSection3AChanged();
    partial void OnCommentSection3BChanging(string value);
    partial void OnCommentSection3BChanged();
    partial void OnCommentSection3CChanging(string value);
    partial void OnCommentSection3CChanged();
    partial void OnCommentSection3DChanging(string value);
    partial void OnCommentSection3DChanged();
    partial void OnCommentSection3EChanging(string value);
    partial void OnCommentSection3EChanged();
    partial void OnCommentSection3FChanging(string value);
    partial void OnCommentSection3FChanged();
    partial void OnDaysSickChanging(System.Nullable<int> value);
    partial void OnDaysSickChanged();
    partial void OnDaysTardyChanging(System.Nullable<int> value);
    partial void OnDaysTardyChanged();
    partial void OnprimeCommentsChanging(string value);
    partial void OnprimeCommentsChanged();
    partial void OnNextEvaluationDateChanging(string value);
    partial void OnNextEvaluationDateChanged();
    partial void OnEnableManagerStrengthChanging(string value);
    partial void OnEnableManagerStrengthChanged();
    partial void OnEnableNeedImprovementChanging(string value);
    partial void OnEnableNeedImprovementChanged();
    partial void OnEnableRemarksChanging(string value);
    partial void OnEnableRemarksChanged();
    #endregion
		
		public EvaluationLINQ()
		{
			this._Evaluation_Scores = new EntitySet<Evaluation_Score>(new Action<Evaluation_Score>(this.attach_Evaluation_Scores), new Action<Evaluation_Score>(this.detach_Evaluation_Scores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluationType", DbType="VarChar(MAX)")]
		public string EvaluationType
		{
			get
			{
				return this._EvaluationType;
			}
			set
			{
				if ((this._EvaluationType != value))
				{
					this.OnEvaluationTypeChanging(value);
					this.SendPropertyChanging();
					this._EvaluationType = value;
					this.SendPropertyChanged("EvaluationType");
					this.OnEvaluationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluatedById", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EvaluatedById
		{
			get
			{
				return this._EvaluatedById;
			}
			set
			{
				if ((this._EvaluatedById != value))
				{
					this.OnEvaluatedByIdChanging(value);
					this.SendPropertyChanging();
					this._EvaluatedById = value;
					this.SendPropertyChanged("EvaluatedById");
					this.OnEvaluatedByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEvaluated", DbType="VarChar(50)")]
		public string DateEvaluated
		{
			get
			{
				return this._DateEvaluated;
			}
			set
			{
				if ((this._DateEvaluated != value))
				{
					this.OnDateEvaluatedChanging(value);
					this.SendPropertyChanging();
					this._DateEvaluated = value;
					this.SendPropertyChanged("DateEvaluated");
					this.OnDateEvaluatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalScore", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalScore
		{
			get
			{
				return this._TotalScore;
			}
			set
			{
				if ((this._TotalScore != value))
				{
					this.OnTotalScoreChanging(value);
					this.SendPropertyChanging();
					this._TotalScore = value;
					this.SendPropertyChanged("TotalScore");
					this.OnTotalScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarksName", DbType="VarChar(50)")]
		public string RemarksName
		{
			get
			{
				return this._RemarksName;
			}
			set
			{
				if ((this._RemarksName != value))
				{
					this.OnRemarksNameChanging(value);
					this.SendPropertyChanging();
					this._RemarksName = value;
					this.SendPropertyChanged("RemarksName");
					this.OnRemarksNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpUnacceptable", DbType="VarChar(MAX)")]
		public string ImpUnacceptable
		{
			get
			{
				return this._ImpUnacceptable;
			}
			set
			{
				if ((this._ImpUnacceptable != value))
				{
					this.OnImpUnacceptableChanging(value);
					this.SendPropertyChanging();
					this._ImpUnacceptable = value;
					this.SendPropertyChanged("ImpUnacceptable");
					this.OnImpUnacceptableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpFallShort", DbType="VarChar(MAX)")]
		public string ImpFallShort
		{
			get
			{
				return this._ImpFallShort;
			}
			set
			{
				if ((this._ImpFallShort != value))
				{
					this.OnImpFallShortChanging(value);
					this.SendPropertyChanging();
					this._ImpFallShort = value;
					this.SendPropertyChanged("ImpFallShort");
					this.OnImpFallShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpEffective", DbType="VarChar(MAX)")]
		public string ImpEffective
		{
			get
			{
				return this._ImpEffective;
			}
			set
			{
				if ((this._ImpEffective != value))
				{
					this.OnImpEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ImpEffective = value;
					this.SendPropertyChanged("ImpEffective");
					this.OnImpEffectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpHighlyEffective", DbType="VarChar(MAX)")]
		public string ImpHighlyEffective
		{
			get
			{
				return this._ImpHighlyEffective;
			}
			set
			{
				if ((this._ImpHighlyEffective != value))
				{
					this.OnImpHighlyEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ImpHighlyEffective = value;
					this.SendPropertyChanged("ImpHighlyEffective");
					this.OnImpHighlyEffectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpExceptional", DbType="VarChar(MAX)")]
		public string ImpExceptional
		{
			get
			{
				return this._ImpExceptional;
			}
			set
			{
				if ((this._ImpExceptional != value))
				{
					this.OnImpExceptionalChanging(value);
					this.SendPropertyChanging();
					this._ImpExceptional = value;
					this.SendPropertyChanged("ImpExceptional");
					this.OnImpExceptionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recommendation", DbType="VarChar(MAX)")]
		public string Recommendation
		{
			get
			{
				return this._Recommendation;
			}
			set
			{
				if ((this._Recommendation != value))
				{
					this.OnRecommendationChanging(value);
					this.SendPropertyChanging();
					this._Recommendation = value;
					this.SendPropertyChanged("Recommendation");
					this.OnRecommendationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedImprovement", DbType="VarChar(MAX)")]
		public string NeedImprovement
		{
			get
			{
				return this._NeedImprovement;
			}
			set
			{
				if ((this._NeedImprovement != value))
				{
					this.OnNeedImprovementChanging(value);
					this.SendPropertyChanging();
					this._NeedImprovement = value;
					this.SendPropertyChanged("NeedImprovement");
					this.OnNeedImprovementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedByManagerId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ApprovedByManagerId
		{
			get
			{
				return this._ApprovedByManagerId;
			}
			set
			{
				if ((this._ApprovedByManagerId != value))
				{
					this.OnApprovedByManagerIdChanging(value);
					this.SendPropertyChanging();
					this._ApprovedByManagerId = value;
					this.SendPropertyChanged("ApprovedByManagerId");
					this.OnApprovedByManagerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedByHRId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ApprovedByHRId
		{
			get
			{
				return this._ApprovedByHRId;
			}
			set
			{
				if ((this._ApprovedByHRId != value))
				{
					this.OnApprovedByHRIdChanging(value);
					this.SendPropertyChanging();
					this._ApprovedByHRId = value;
					this.SendPropertyChanged("ApprovedByHRId");
					this.OnApprovedByHRIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesCreativeContribution", DbType="VarChar(MAX)")]
		public string EmployeesCreativeContribution
		{
			get
			{
				return this._EmployeesCreativeContribution;
			}
			set
			{
				if ((this._EmployeesCreativeContribution != value))
				{
					this.OnEmployeesCreativeContributionChanging(value);
					this.SendPropertyChanging();
					this._EmployeesCreativeContribution = value;
					this.SendPropertyChanged("EmployeesCreativeContribution");
					this.OnEmployeesCreativeContributionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesNewSkills", DbType="VarChar(MAX)")]
		public string EmployeesNewSkills
		{
			get
			{
				return this._EmployeesNewSkills;
			}
			set
			{
				if ((this._EmployeesNewSkills != value))
				{
					this.OnEmployeesNewSkillsChanging(value);
					this.SendPropertyChanging();
					this._EmployeesNewSkills = value;
					this.SendPropertyChanged("EmployeesNewSkills");
					this.OnEmployeesNewSkillsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesStrength", DbType="VarChar(MAX)")]
		public string EmployeesStrength
		{
			get
			{
				return this._EmployeesStrength;
			}
			set
			{
				if ((this._EmployeesStrength != value))
				{
					this.OnEmployeesStrengthChanging(value);
					this.SendPropertyChanging();
					this._EmployeesStrength = value;
					this.SendPropertyChanged("EmployeesStrength");
					this.OnEmployeesStrengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesImprovement", DbType="VarChar(MAX)")]
		public string EmployeesImprovement
		{
			get
			{
				return this._EmployeesImprovement;
			}
			set
			{
				if ((this._EmployeesImprovement != value))
				{
					this.OnEmployeesImprovementChanging(value);
					this.SendPropertyChanging();
					this._EmployeesImprovement = value;
					this.SendPropertyChanged("EmployeesImprovement");
					this.OnEmployeesImprovementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesChanges", DbType="VarChar(MAX)")]
		public string EmployeesChanges
		{
			get
			{
				return this._EmployeesChanges;
			}
			set
			{
				if ((this._EmployeesChanges != value))
				{
					this.OnEmployeesChangesChanging(value);
					this.SendPropertyChanging();
					this._EmployeesChanges = value;
					this.SendPropertyChanged("EmployeesChanges");
					this.OnEmployeesChangesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesPersonalGoals", DbType="VarChar(MAX)")]
		public string EmployeesPersonalGoals
		{
			get
			{
				return this._EmployeesPersonalGoals;
			}
			set
			{
				if ((this._EmployeesPersonalGoals != value))
				{
					this.OnEmployeesPersonalGoalsChanging(value);
					this.SendPropertyChanging();
					this._EmployeesPersonalGoals = value;
					this.SendPropertyChanged("EmployeesPersonalGoals");
					this.OnEmployeesPersonalGoalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesRecommendation", DbType="VarChar(MAX)")]
		public string EmployeesRecommendation
		{
			get
			{
				return this._EmployeesRecommendation;
			}
			set
			{
				if ((this._EmployeesRecommendation != value))
				{
					this.OnEmployeesRecommendationChanging(value);
					this.SendPropertyChanging();
					this._EmployeesRecommendation = value;
					this.SendPropertyChanged("EmployeesRecommendation");
					this.OnEmployeesRecommendationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agency", DbType="VarChar(MAX)")]
		public string Agency
		{
			get
			{
				return this._Agency;
			}
			set
			{
				if ((this._Agency != value))
				{
					this.OnAgencyChanging(value);
					this.SendPropertyChanging();
					this._Agency = value;
					this.SendPropertyChanged("Agency");
					this.OnAgencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section1A", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section1A
		{
			get
			{
				return this._Section1A;
			}
			set
			{
				if ((this._Section1A != value))
				{
					this.OnSection1AChanging(value);
					this.SendPropertyChanging();
					this._Section1A = value;
					this.SendPropertyChanged("Section1A");
					this.OnSection1AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section1B", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section1B
		{
			get
			{
				return this._Section1B;
			}
			set
			{
				if ((this._Section1B != value))
				{
					this.OnSection1BChanging(value);
					this.SendPropertyChanging();
					this._Section1B = value;
					this.SendPropertyChanged("Section1B");
					this.OnSection1BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section1C", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section1C
		{
			get
			{
				return this._Section1C;
			}
			set
			{
				if ((this._Section1C != value))
				{
					this.OnSection1CChanging(value);
					this.SendPropertyChanging();
					this._Section1C = value;
					this.SendPropertyChanged("Section1C");
					this.OnSection1CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section2A", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section2A
		{
			get
			{
				return this._Section2A;
			}
			set
			{
				if ((this._Section2A != value))
				{
					this.OnSection2AChanging(value);
					this.SendPropertyChanging();
					this._Section2A = value;
					this.SendPropertyChanged("Section2A");
					this.OnSection2AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section2B", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section2B
		{
			get
			{
				return this._Section2B;
			}
			set
			{
				if ((this._Section2B != value))
				{
					this.OnSection2BChanging(value);
					this.SendPropertyChanging();
					this._Section2B = value;
					this.SendPropertyChanged("Section2B");
					this.OnSection2BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section2C", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section2C
		{
			get
			{
				return this._Section2C;
			}
			set
			{
				if ((this._Section2C != value))
				{
					this.OnSection2CChanging(value);
					this.SendPropertyChanging();
					this._Section2C = value;
					this.SendPropertyChanged("Section2C");
					this.OnSection2CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3A", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3A
		{
			get
			{
				return this._Section3A;
			}
			set
			{
				if ((this._Section3A != value))
				{
					this.OnSection3AChanging(value);
					this.SendPropertyChanging();
					this._Section3A = value;
					this.SendPropertyChanged("Section3A");
					this.OnSection3AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3B", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3B
		{
			get
			{
				return this._Section3B;
			}
			set
			{
				if ((this._Section3B != value))
				{
					this.OnSection3BChanging(value);
					this.SendPropertyChanging();
					this._Section3B = value;
					this.SendPropertyChanged("Section3B");
					this.OnSection3BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3C", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3C
		{
			get
			{
				return this._Section3C;
			}
			set
			{
				if ((this._Section3C != value))
				{
					this.OnSection3CChanging(value);
					this.SendPropertyChanging();
					this._Section3C = value;
					this.SendPropertyChanged("Section3C");
					this.OnSection3CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3D", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3D
		{
			get
			{
				return this._Section3D;
			}
			set
			{
				if ((this._Section3D != value))
				{
					this.OnSection3DChanging(value);
					this.SendPropertyChanging();
					this._Section3D = value;
					this.SendPropertyChanged("Section3D");
					this.OnSection3DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3E", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3E
		{
			get
			{
				return this._Section3E;
			}
			set
			{
				if ((this._Section3E != value))
				{
					this.OnSection3EChanging(value);
					this.SendPropertyChanging();
					this._Section3E = value;
					this.SendPropertyChanged("Section3E");
					this.OnSection3EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section3F", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Section3F
		{
			get
			{
				return this._Section3F;
			}
			set
			{
				if ((this._Section3F != value))
				{
					this.OnSection3FChanging(value);
					this.SendPropertyChanging();
					this._Section3F = value;
					this.SendPropertyChanged("Section3F");
					this.OnSection3FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection1A", DbType="VarChar(MAX)")]
		public string CommentSection1A
		{
			get
			{
				return this._CommentSection1A;
			}
			set
			{
				if ((this._CommentSection1A != value))
				{
					this.OnCommentSection1AChanging(value);
					this.SendPropertyChanging();
					this._CommentSection1A = value;
					this.SendPropertyChanged("CommentSection1A");
					this.OnCommentSection1AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection1B", DbType="VarChar(MAX)")]
		public string CommentSection1B
		{
			get
			{
				return this._CommentSection1B;
			}
			set
			{
				if ((this._CommentSection1B != value))
				{
					this.OnCommentSection1BChanging(value);
					this.SendPropertyChanging();
					this._CommentSection1B = value;
					this.SendPropertyChanged("CommentSection1B");
					this.OnCommentSection1BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection1C", DbType="VarChar(MAX)")]
		public string CommentSection1C
		{
			get
			{
				return this._CommentSection1C;
			}
			set
			{
				if ((this._CommentSection1C != value))
				{
					this.OnCommentSection1CChanging(value);
					this.SendPropertyChanging();
					this._CommentSection1C = value;
					this.SendPropertyChanged("CommentSection1C");
					this.OnCommentSection1CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection2A", DbType="VarChar(MAX)")]
		public string CommentSection2A
		{
			get
			{
				return this._CommentSection2A;
			}
			set
			{
				if ((this._CommentSection2A != value))
				{
					this.OnCommentSection2AChanging(value);
					this.SendPropertyChanging();
					this._CommentSection2A = value;
					this.SendPropertyChanged("CommentSection2A");
					this.OnCommentSection2AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection2B", DbType="VarChar(MAX)")]
		public string CommentSection2B
		{
			get
			{
				return this._CommentSection2B;
			}
			set
			{
				if ((this._CommentSection2B != value))
				{
					this.OnCommentSection2BChanging(value);
					this.SendPropertyChanging();
					this._CommentSection2B = value;
					this.SendPropertyChanged("CommentSection2B");
					this.OnCommentSection2BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection2C", DbType="VarChar(MAX)")]
		public string CommentSection2C
		{
			get
			{
				return this._CommentSection2C;
			}
			set
			{
				if ((this._CommentSection2C != value))
				{
					this.OnCommentSection2CChanging(value);
					this.SendPropertyChanging();
					this._CommentSection2C = value;
					this.SendPropertyChanged("CommentSection2C");
					this.OnCommentSection2CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3A", DbType="VarChar(MAX)")]
		public string CommentSection3A
		{
			get
			{
				return this._CommentSection3A;
			}
			set
			{
				if ((this._CommentSection3A != value))
				{
					this.OnCommentSection3AChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3A = value;
					this.SendPropertyChanged("CommentSection3A");
					this.OnCommentSection3AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3B", DbType="VarChar(MAX)")]
		public string CommentSection3B
		{
			get
			{
				return this._CommentSection3B;
			}
			set
			{
				if ((this._CommentSection3B != value))
				{
					this.OnCommentSection3BChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3B = value;
					this.SendPropertyChanged("CommentSection3B");
					this.OnCommentSection3BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3C", DbType="VarChar(MAX)")]
		public string CommentSection3C
		{
			get
			{
				return this._CommentSection3C;
			}
			set
			{
				if ((this._CommentSection3C != value))
				{
					this.OnCommentSection3CChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3C = value;
					this.SendPropertyChanged("CommentSection3C");
					this.OnCommentSection3CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3D", DbType="VarChar(MAX)")]
		public string CommentSection3D
		{
			get
			{
				return this._CommentSection3D;
			}
			set
			{
				if ((this._CommentSection3D != value))
				{
					this.OnCommentSection3DChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3D = value;
					this.SendPropertyChanged("CommentSection3D");
					this.OnCommentSection3DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3E", DbType="VarChar(MAX)")]
		public string CommentSection3E
		{
			get
			{
				return this._CommentSection3E;
			}
			set
			{
				if ((this._CommentSection3E != value))
				{
					this.OnCommentSection3EChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3E = value;
					this.SendPropertyChanged("CommentSection3E");
					this.OnCommentSection3EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentSection3F", DbType="VarChar(MAX)")]
		public string CommentSection3F
		{
			get
			{
				return this._CommentSection3F;
			}
			set
			{
				if ((this._CommentSection3F != value))
				{
					this.OnCommentSection3FChanging(value);
					this.SendPropertyChanging();
					this._CommentSection3F = value;
					this.SendPropertyChanged("CommentSection3F");
					this.OnCommentSection3FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysSick", DbType="Int")]
		public System.Nullable<int> DaysSick
		{
			get
			{
				return this._DaysSick;
			}
			set
			{
				if ((this._DaysSick != value))
				{
					this.OnDaysSickChanging(value);
					this.SendPropertyChanging();
					this._DaysSick = value;
					this.SendPropertyChanged("DaysSick");
					this.OnDaysSickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysTardy", DbType="Int")]
		public System.Nullable<int> DaysTardy
		{
			get
			{
				return this._DaysTardy;
			}
			set
			{
				if ((this._DaysTardy != value))
				{
					this.OnDaysTardyChanging(value);
					this.SendPropertyChanging();
					this._DaysTardy = value;
					this.SendPropertyChanged("DaysTardy");
					this.OnDaysTardyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primeComments", DbType="VarChar(MAX)")]
		public string primeComments
		{
			get
			{
				return this._primeComments;
			}
			set
			{
				if ((this._primeComments != value))
				{
					this.OnprimeCommentsChanging(value);
					this.SendPropertyChanging();
					this._primeComments = value;
					this.SendPropertyChanged("primeComments");
					this.OnprimeCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextEvaluationDate", DbType="VarChar(50)")]
		public string NextEvaluationDate
		{
			get
			{
				return this._NextEvaluationDate;
			}
			set
			{
				if ((this._NextEvaluationDate != value))
				{
					this.OnNextEvaluationDateChanging(value);
					this.SendPropertyChanging();
					this._NextEvaluationDate = value;
					this.SendPropertyChanged("NextEvaluationDate");
					this.OnNextEvaluationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableManagerStrength", DbType="VarChar(MAX)")]
		public string EnableManagerStrength
		{
			get
			{
				return this._EnableManagerStrength;
			}
			set
			{
				if ((this._EnableManagerStrength != value))
				{
					this.OnEnableManagerStrengthChanging(value);
					this.SendPropertyChanging();
					this._EnableManagerStrength = value;
					this.SendPropertyChanged("EnableManagerStrength");
					this.OnEnableManagerStrengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableNeedImprovement", DbType="VarChar(MAX)")]
		public string EnableNeedImprovement
		{
			get
			{
				return this._EnableNeedImprovement;
			}
			set
			{
				if ((this._EnableNeedImprovement != value))
				{
					this.OnEnableNeedImprovementChanging(value);
					this.SendPropertyChanging();
					this._EnableNeedImprovement = value;
					this.SendPropertyChanged("EnableNeedImprovement");
					this.OnEnableNeedImprovementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableRemarks", DbType="VarChar(MAX)")]
		public string EnableRemarks
		{
			get
			{
				return this._EnableRemarks;
			}
			set
			{
				if ((this._EnableRemarks != value))
				{
					this.OnEnableRemarksChanging(value);
					this.SendPropertyChanging();
					this._EnableRemarks = value;
					this.SendPropertyChanged("EnableRemarks");
					this.OnEnableRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Evaluation_Evaluation_Score", Storage="_Evaluation_Scores", ThisKey="Id", OtherKey="EvaluationId")]
		public EntitySet<Evaluation_Score> Evaluation_Scores
		{
			get
			{
				return this._Evaluation_Scores;
			}
			set
			{
				this._Evaluation_Scores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Evaluation_Scores(Evaluation_Score entity)
		{
			this.SendPropertyChanging();
			entity.EvaluationLINQ = this;
		}
		
		private void detach_Evaluation_Scores(Evaluation_Score entity)
		{
			this.SendPropertyChanging();
			entity.EvaluationLINQ = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Evaluation_Score")]
	public partial class Evaluation_Score : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _EvaluationId;
		
		private System.Nullable<int> _CompetenceCatId;
		
		private System.Nullable<decimal> _Rating;
		
		private System.Nullable<int> _CompetenceCatQId;
		
		private System.Nullable<decimal> _StaffRating;
		
		private System.Nullable<decimal> _EvaluatorRating;
		
		private System.Nullable<decimal> _TotalRating;
		
		private string _Remarks;
		
		private EntityRef<EvaluationLINQ> _EvaluationLINQ;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEvaluationIdChanging(System.Nullable<int> value);
    partial void OnEvaluationIdChanged();
    partial void OnCompetenceCatIdChanging(System.Nullable<int> value);
    partial void OnCompetenceCatIdChanged();
    partial void OnRatingChanging(System.Nullable<decimal> value);
    partial void OnRatingChanged();
    partial void OnCompetenceCatQIdChanging(System.Nullable<int> value);
    partial void OnCompetenceCatQIdChanged();
    partial void OnStaffRatingChanging(System.Nullable<decimal> value);
    partial void OnStaffRatingChanged();
    partial void OnEvaluatorRatingChanging(System.Nullable<decimal> value);
    partial void OnEvaluatorRatingChanged();
    partial void OnTotalRatingChanging(System.Nullable<decimal> value);
    partial void OnTotalRatingChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    #endregion
		
		public Evaluation_Score()
		{
			this._EvaluationLINQ = default(EntityRef<EvaluationLINQ>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluationId", DbType="Int")]
		public System.Nullable<int> EvaluationId
		{
			get
			{
				return this._EvaluationId;
			}
			set
			{
				if ((this._EvaluationId != value))
				{
					if (this._EvaluationLINQ.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEvaluationIdChanging(value);
					this.SendPropertyChanging();
					this._EvaluationId = value;
					this.SendPropertyChanged("EvaluationId");
					this.OnEvaluationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetenceCatId", DbType="Int")]
		public System.Nullable<int> CompetenceCatId
		{
			get
			{
				return this._CompetenceCatId;
			}
			set
			{
				if ((this._CompetenceCatId != value))
				{
					this.OnCompetenceCatIdChanging(value);
					this.SendPropertyChanging();
					this._CompetenceCatId = value;
					this.SendPropertyChanged("CompetenceCatId");
					this.OnCompetenceCatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetenceCatQId", DbType="Int")]
		public System.Nullable<int> CompetenceCatQId
		{
			get
			{
				return this._CompetenceCatQId;
			}
			set
			{
				if ((this._CompetenceCatQId != value))
				{
					this.OnCompetenceCatQIdChanging(value);
					this.SendPropertyChanging();
					this._CompetenceCatQId = value;
					this.SendPropertyChanged("CompetenceCatQId");
					this.OnCompetenceCatQIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffRating", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> StaffRating
		{
			get
			{
				return this._StaffRating;
			}
			set
			{
				if ((this._StaffRating != value))
				{
					this.OnStaffRatingChanging(value);
					this.SendPropertyChanging();
					this._StaffRating = value;
					this.SendPropertyChanged("StaffRating");
					this.OnStaffRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluatorRating", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> EvaluatorRating
		{
			get
			{
				return this._EvaluatorRating;
			}
			set
			{
				if ((this._EvaluatorRating != value))
				{
					this.OnEvaluatorRatingChanging(value);
					this.SendPropertyChanging();
					this._EvaluatorRating = value;
					this.SendPropertyChanged("EvaluatorRating");
					this.OnEvaluatorRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRating", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalRating
		{
			get
			{
				return this._TotalRating;
			}
			set
			{
				if ((this._TotalRating != value))
				{
					this.OnTotalRatingChanging(value);
					this.SendPropertyChanging();
					this._TotalRating = value;
					this.SendPropertyChanged("TotalRating");
					this.OnTotalRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Evaluation_Evaluation_Score", Storage="_EvaluationLINQ", ThisKey="EvaluationId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public EvaluationLINQ EvaluationLINQ
		{
			get
			{
				return this._EvaluationLINQ.Entity;
			}
			set
			{
				EvaluationLINQ previousValue = this._EvaluationLINQ.Entity;
				if (((previousValue != value) 
							|| (this._EvaluationLINQ.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EvaluationLINQ.Entity = null;
						previousValue.Evaluation_Scores.Remove(this);
					}
					this._EvaluationLINQ.Entity = value;
					if ((value != null))
					{
						value.Evaluation_Scores.Add(this);
						this._EvaluationId = value.Id;
					}
					else
					{
						this._EvaluationId = default(Nullable<int>);
					}
					this.SendPropertyChanged("EvaluationLINQ");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
