<?xml version="1.0" encoding="utf-8"?><Database Name="dbAMS" Class="eHRISContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=dbAMS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbAMS" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Role_UsersInRole" Member="UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UsersInRole" />
      <Association Name="Role_POSITION" Member="POSITIONs" ThisKey="RoleId" OtherKey="RoleId" Type="POSITION" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluation" Member="EvaluationLINQs">
    <Type Name="EvaluationLINQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EvaluationType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EvaluatedById" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateEvaluated" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalScore" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="RemarksName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImpUnacceptable" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImpFallShort" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImpEffective" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImpHighlyEffective" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImpExceptional" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Recommendation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NeedImprovement" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ApprovedByManagerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ApprovedByHRId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmployeesCreativeContribution" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesNewSkills" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesStrength" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesImprovement" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesChanges" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesPersonalGoals" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeesRecommendation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Agency" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Section1A" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section1B" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section1C" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section2A" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section2B" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section2C" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3A" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3B" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3C" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3D" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3E" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Section3F" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CommentSection1A" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection1B" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection1C" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection2A" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection2B" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection2C" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3A" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3B" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3C" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3D" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3E" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentSection3F" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DaysSick" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaysTardy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="primeComments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NextEvaluationDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EnableManagerStrength" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EnableNeedImprovement" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EnableRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="EvaluationLINQ_Evaluation_Score" Member="Evaluation_Scores" ThisKey="Id" OtherKey="EvaluationId" Type="Evaluation_Score" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluation_Score" Member="Evaluation_Scores">
    <Type Name="Evaluation_Score">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EvaluationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompetenceCatId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rating" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CompetenceCatQId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffRating" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="EvaluatorRating" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalRating" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="EvaluationLINQ_Evaluation_Score" Member="EvaluationLINQ" ThisKey="EvaluationId" OtherKey="Id" Type="EvaluationLINQ" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Memberships" Member="MembershipLINQs">
    <Type Name="MembershipLINQ">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowsStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="MembershipLINQ_EMPLOYEE" Member="EMPLOYEE" ThisKey="UserId" OtherKey="UserId" Type="EMPLOYEE" Cardinality="One" />
      <Association Name="User_MembershipLINQ" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_MembershipLINQ" Member="MembershipLINQ" ThisKey="UserId" OtherKey="UserId" Type="MembershipLINQ" Cardinality="One" />
      <Association Name="User_UsersInRole" Member="UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.UsersInRoles" Member="UsersInRoles">
    <Type Name="UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UsersInRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UsersInRole" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiteStatus" Member="SiteStatus">
    <Type Name="SiteStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SetValue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Emp_Id" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="M_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NationalityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BloodType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Emp_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubUnit" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contract_SD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contract_ED" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAccountStatusModified" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="MembershipLINQ_EMPLOYEE" Member="MembershipLINQ" ThisKey="UserId" OtherKey="UserId" Type="MembershipLINQ" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="POSITION_EMPLOYEE" Member="POSITION" ThisKey="PositionId" OtherKey="Id" Type="POSITION" IsForeignKey="true" />
      <Association Name="AGENCY_EMPLOYEE" Member="AGENCY" ThisKey="AgencyId" OtherKey="Id" Type="AGENCY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.POSITION" Member="POSITIONs">
    <Type Name="POSITION">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Position" Member="Position1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="POSITION_EMPLOYEE" Member="EMPLOYEEs" ThisKey="Id" OtherKey="PositionId" Type="EMPLOYEE" />
      <Association Name="Role_POSITION" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="DEPARTMENT_POSITION" Member="DEPARTMENT" ThisKey="DepartmentId" OtherKey="Id" Type="DEPARTMENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DEPARTMENT" Member="DEPARTMENTs">
    <Type Name="DEPARTMENT">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Department" Member="Department1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="DEPARTMENT_POSITION" Member="POSITIONs" ThisKey="Id" OtherKey="DepartmentId" Type="POSITION" />
    </Type>
  </Table>
  <Table Name="dbo.AGENCY" Member="AGENCies">
    <Type Name="AGENCY">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Agency" Member="Agency1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="AGENCY_EMPLOYEE" Member="EMPLOYEEs" ThisKey="Id" OtherKey="AgencyId" Type="EMPLOYEE" />
    </Type>
  </Table>
  <Table Name="dbo.LeaveType" Member="LeaveTypes">
    <Type Name="LeaveType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeaveName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DefaultDays" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AgencyId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LeaveType_LeaveTypeUser" Member="LeaveTypeUsers" ThisKey="Id" OtherKey="LeaveTypeId" Type="LeaveTypeUser" />
    </Type>
  </Table>
  <Table Name="dbo.LeaveTypeUser" Member="LeaveTypeUsers">
    <Type Name="LeaveTypeUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LeaveTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoOfDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LeaveTypeUser_LeaveTransaction" Member="LeaveTransactions" ThisKey="Id" OtherKey="LeaveTypeUserId" Type="LeaveTransaction" />
      <Association Name="LeaveType_LeaveTypeUser" Member="LeaveType" ThisKey="LeaveTypeId" OtherKey="Id" Type="LeaveType" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.LeaveTransaction" Member="LeaveTransactions">
    <Type Name="LeaveTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeaveTypeUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfDays" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentHeadApproval" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HRApproval" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FiledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LeaveTypeUser_LeaveTransaction" Member="LeaveTypeUser" ThisKey="LeaveTypeUserId" OtherKey="Id" Type="LeaveTypeUser" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>